defmodule JsonLiveviewRender.Catalog.PropDef do
  @moduledoc "Prop definition metadata used by catalog components."

  @enforce_keys [:name, :type]
  defstruct [
    :name,
    :type,
    :doc,
    :validator,
    :binding_type,
    required: false,
    default: nil,
    values: nil
  ]

  @type prop_type ::
          :string
          | :integer
          | :float
          | :boolean
          | :map
          | :custom
          | :enum
          | {:list, prop_type()}

  @type t :: %__MODULE__{
          name: atom(),
          type: prop_type(),
          required: boolean(),
          default: term(),
          doc: String.t() | nil,
          values: [term()] | nil,
          validator: (term() -> boolean()) | nil,
          binding_type: prop_type() | nil
        }

  @doc "Returns true if `value` satisfies the type contract defined by `prop_def`."
  @spec valid?(term(), t()) :: boolean()
  def valid?(nil, %__MODULE__{required: false}), do: true
  def valid?(nil, _), do: false
  def valid?(value, %__MODULE__{type: :string}), do: is_binary(value)
  def valid?(value, %__MODULE__{type: :integer}), do: is_integer(value)
  def valid?(value, %__MODULE__{type: :float}), do: is_integer(value) or is_float(value)
  def valid?(value, %__MODULE__{type: :boolean}), do: is_boolean(value)
  def valid?(value, %__MODULE__{type: :map}), do: is_map(value)

  def valid?(value, %__MODULE__{type: :enum, values: values}) do
    values = values || []
    value in values or to_string(value) in Enum.map(values, &to_string/1)
  end

  def valid?(value, %__MODULE__{type: {:list, inner}}) when is_list(value) do
    Enum.all?(value, fn item -> valid?(item, %__MODULE__{name: :_item, type: inner}) end)
  end

  def valid?(value, %__MODULE__{type: :custom, validator: validator})
      when is_function(validator, 1),
      do: validator.(value)

  def valid?(_value, _prop), do: false
end

defmodule JsonLiveviewRender.Catalog.ComponentDef do
  @moduledoc "Component definition generated by `JsonLiveviewRender.Catalog` DSL."

  alias JsonLiveviewRender.Catalog.PropDef

  @enforce_keys [:name]
  defstruct [
    :name,
    description: nil,
    props: %{},
    slots: [],
    permission: nil,
    defaults: %{},
    prop_key_set: MapSet.new(),
    assign_key_map: %{}
  ]

  @type t :: %__MODULE__{
          name: atom(),
          description: String.t() | nil,
          props: %{optional(atom()) => PropDef.t()},
          slots: [atom()],
          permission: term() | nil,
          defaults: %{optional(String.t()) => term()},
          prop_key_set: MapSet.t(String.t()),
          assign_key_map: %{optional(String.t()) => atom()}
        }

  @doc "Creates a new component definition with the given name."
  @spec new(atom()) :: t()
  def new(name) when is_atom(name), do: %__MODULE__{name: name}

  @doc "Sets the human-readable description on a component definition."
  @spec put_description(t(), String.t()) :: t()
  def put_description(component, description) when is_binary(description) do
    %{component | description: description}
  end

  @doc "Adds or replaces a prop definition on the component."
  @spec put_prop(t(), PropDef.t()) :: t()
  def put_prop(component, %PropDef{name: prop_name} = prop) do
    %{component | props: Map.put(component.props, prop_name, prop)}
  end

  @doc "Appends a named slot to the component's slot list (deduplicated)."
  @spec put_slot(t(), atom()) :: t()
  def put_slot(component, slot_name) when is_atom(slot_name) do
    %{component | slots: Enum.uniq(component.slots ++ [slot_name])}
  end

  @doc "Sets the required permission role for the component."
  @spec put_permission(t(), term()) :: t()
  def put_permission(component, required_role) do
    %{component | permission: required_role}
  end

  @doc "Returns sorted prop names for the component."
  @spec prop_names(t()) :: [atom()]
  def prop_names(component), do: component.props |> Map.keys() |> Enum.sort()

  @doc "Returns cached default props or derives them from `props` when absent."
  @spec defaults(t()) :: %{optional(String.t()) => term()}
  def defaults(%__MODULE__{defaults: defaults} = component) do
    if metadata_cached?(component) do
      defaults
    else
      component |> derive_prop_metadata() |> elem(0)
    end
  end

  @doc "Returns cached string prop keys or derives them from `props` when absent."
  @spec prop_key_set(t()) :: MapSet.t(String.t())
  def prop_key_set(%__MODULE__{prop_key_set: prop_key_set, props: props} = component) do
    if MapSet.size(prop_key_set) > 0 or props == %{} do
      prop_key_set
    else
      component |> derive_prop_metadata() |> elem(1)
    end
  end

  @doc "Returns cached assign mappings or derives them from `props` when absent."
  @spec assign_key_map(t()) :: %{optional(String.t()) => atom()}
  def assign_key_map(%__MODULE__{assign_key_map: assign_key_map, props: props} = component) do
    if assign_key_map != %{} or props == %{} do
      assign_key_map
    else
      component |> derive_prop_metadata() |> elem(2)
    end
  end

  @doc "Finalizes derived prop metadata used by validation and rendering hot paths."
  @spec finalize(t()) :: t()
  def finalize(%__MODULE__{} = component) do
    {defaults, prop_key_set, assign_key_map} = derive_prop_metadata(component)

    component
    |> Map.put(:defaults, defaults)
    |> Map.put(:prop_key_set, prop_key_set)
    |> Map.put(:assign_key_map, assign_key_map)
  end

  defp derive_prop_metadata(%__MODULE__{props: props}) do
    Enum.reduce(props, {%{}, MapSet.new(), %{}}, fn {prop_name, prop_def},
                                                    {defaults, prop_key_set, assign_key_map} ->
      key = Atom.to_string(prop_name)

      defaults =
        if is_nil(prop_def.default) do
          defaults
        else
          Map.put(defaults, key, prop_def.default)
        end

      assign_key_map =
        if String.ends_with?(key, "_binding") do
          assign_key_map
          |> Map.put(key, prop_name)
          |> Map.put(
            String.replace_suffix(key, "_binding", ""),
            String.to_atom(String.replace_suffix(key, "_binding", ""))
          )
        else
          Map.put(assign_key_map, key, prop_name)
        end

      {defaults, MapSet.put(prop_key_set, key), assign_key_map}
    end)
  end

  defp metadata_cached?(%__MODULE__{props: props, prop_key_set: prop_key_set}) do
    props == %{} or MapSet.size(prop_key_set) == map_size(props)
  end
end
